### ISSUE TITLE
CHiLO-Speechアドインのデザイン調整

### ISSUE THREAD

**Issue by ties-taguchi** [npocccties/chilospeech#16]
CHiLO-Speechアドインのデザインを見て，以下が気になったので調整希望です．
・タグの例とボタンがくっついてるので，2〜3ピクセル程空けて欲しい
・ボタン内のアイコンが右端すぎるので，設定可能なら少しだけ間を空けて欲しい
![image (15)](https://user-images.githubusercontent.com/9006111/140438991-2001e418-97b5-4679-b3f5-43442fd5ccb9.png)

**Comment by ties-mitsuhashi** [comment]
調整済みと思われるので終了にします．
