### ISSUE TITLE
web版のパワーポイントでCHiLO-Speechのタグコピーが出来ない

### ISSUE THREAD

**Issue by ties-taguchi** [npocccties/chilospeech#20]
### そのバグについて

web版のパワーポイントでCHiLO-Speechのタグコピーが出来ない

### 再現手順

1. CHiLO-Speechアドインを開く
2. よく使うタグをクリックする
3. ペーストする

### 期待していた動作

web版アドインでタグのクリック後にペーストをすると，空のタグをコピー出来る

### デスクトップ再現環境 (下記をうめてください):

- OS: mac
- ブラウザ: chrome
- Version: 96.0.4664.55（Official Build） （x86_64）

**Comment by ties-makimura** [comment]
#21 で対応

> The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details. 

のエラーが出ます．

外部サービスで，iframe許可とかできなさそうなので，とりあえず document.execCommand('copy') でタグのテキストを選択してコピーするようにしました．
パワーポイントのスライド側は影響受けず，選択解除されないので今の所これで問題ないと思います．

**Comment by ties-taguchi** [comment]
web版パワーポイントでの動作を確認しました．

**Comment by ties-taguchi** [comment]
上記Chrome・safari版ともに動作するのを確認しました．
