### ISSUE TITLE
JPEG対応

### ISSUE THREAD

**Issue by horimasumi** [npocccties/chilospeech#3]
Web版パワーポイントのスライド画像の書き出しは，JPEGのみなので，GitHubの画像エンコードもJPEG
対応してほしい．

**Comment by ties-makimura** [comment]
実際にWeb版パワーポイントで画像としてダウンロードすると，拡張子は jpg

**Comment by ties-makimura** [comment]
>JPEG特許は現在は解決されている状態のようです。
http://imaokapat.biz/__HPB_Recycled/yougo601-700/yougo_detail603.html
https://xtech.nikkei.com/dm/article/NEWS/20061106/123157/

**Comment by ties-makimura** [comment]
#15 で対応
