### ISSUE TITLE
Fadeの初期値を0にする

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chilospeech#32]
### どのような問題を解決する機能追加でしょうか?

現在Fadeの初期値は1.0となっているが，フェードイン・フェードアウトがあると，映像が崩れてしまう場合がある．

### あなたが望む解決方法について書いてください

Fadeを0とし，初期値では，フェードイン・フェードアウトをなくす．

### 本 issue を close する条件

本件を、終了(close)とする条件について下記から選ぶか、追記をお願いします。

- [x] コードに実装された。
- [x] ドキュメントに反映され、周知された。

**Comment by ties-makimura** [comment]
https://github.com/npocccties/chilospeech/commit/a89fc4962d8ea8e57532bacc4a082fc05fa5008f で対応

**Comment by ties-mitsuhashi** [comment]
CHiLO-Speechマニュアルに初期値を反映しました．
https://docs.cccties.org/chilospeech/narration/text#bideonokishi
