### ISSUE TITLE
textやdescriptionのあとにスペースあると，読み上げられなかったり，解説に反映されなかったりする

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chilospeech#38]
### どのような問題を解決する機能追加でしょうか?

ノート部のtextやdescriptionの開始行の後にスペース文字があると，音声が読み上げられなかったり，descriptionに記載した文章が解説に反映されず，スライド内の文章がそのまま載ってしまう．
記載ミスではあるが，気づきづらい．

開始行の後にスペースがある例：
```
```text 
```

### あなたが望む解決方法について書いてください

textやdescriptionのあとにスペース文字がある場合は，トリムして，正常に処理されるようにする．

### あなたが考えた別解について書いてください

スペース文字がある場合，generate→ppt2video files のところに`unknown block type description `のように警告が出るが，スペース文字が入っているのが分かりづらいので，""で囲むなどして，スペース文字が入っていることがわかりやすくする．

### 本 issue を close する条件

本件を、終了(close)とする条件について下記から選ぶか、追記をお願いします。

- [ ] 議論の結論がでたか? (一定期間結論がでないものは、close 対象となりうる)

- [ ] コードに実装された。
- [ ] ドキュメントに反映され、周知された。
- [ ] 議論が outdate になってしまった。(コメントで特記し、close)

**Comment by ties-makimura** [comment]
8b27328e62528a475b2d5c555812a1eefc677fac で対応
