### ISSUE TITLE
CHiLO-Speechアドインのロゴ

### ISSUE THREAD

**Issue by horimasumi** [npocccties/chilospeech#4]
パワーポイントの，「Show Taskpane」のところに，CHiLO-Speechアドインのロゴ，およびタイトルを表示してほしい．

![image](https://user-images.githubusercontent.com/9005132/139397994-3fee088b-ffec-4ac5-a244-7545adaa9bd1.png)

**Comment by horimasumi** [comment]
タイトル：CHiLO-Speech
説明：ナレーションを確認するためのCHiLO-Speech用アドイン

**Comment by ties-makimura** [comment]
ロゴはそれぞれのサイズと，後必要ならファビコンの画像を置き換えます．

https://github.com/npocccties/chilospeech/tree/main/ppt-addin-vue/public/favicon.ico
https://github.com/npocccties/chilospeech/tree/main/ppt-addin-vue/public/assets/***

**Comment by ties-taguchi** [comment]
@ties-makimura 
icon-16
![icon-16](https://user-images.githubusercontent.com/9006111/139631146-ce8884c7-316b-46de-8069-40b92f74e0f9.png)
icon-32
![icon-32](https://user-images.githubusercontent.com/9006111/139631149-4bd6b061-2c7f-4f22-a530-61a98a68a2f1.png)
icon-64
![icon-64](https://user-images.githubusercontent.com/9006111/139631151-b94d4704-6c04-40e6-9d41-1a2a35f62309.png)
icon-80
![icon-80](https://user-images.githubusercontent.com/9006111/139631153-53a69fac-1662-4991-8467-94b1babbf5e9.png)
icon-128
![icon-128](https://user-images.githubusercontent.com/9006111/139631155-d1c941b3-55ec-4a6a-b6b2-b59eafc5e074.png)
icon-filled
![icon-filled](https://user-images.githubusercontent.com/9006111/139631156-d751ffe4-6943-4b6e-aa14-a4b01924d9b1.png)

**Comment by ties-taguchi** [comment]
@ties-makimura 
icon-16
![icon-16](https://user-images.githubusercontent.com/9006111/139631502-43f598e3-d873-46c4-b83b-872896ae5942.png)
icon-32
![icon-32](https://user-images.githubusercontent.com/9006111/139631505-c718ccb1-df66-426d-a1fa-fb0a4543c9f2.png)
icon-64
![icon-64](https://user-images.githubusercontent.com/9006111/139631506-54aa858b-17fe-4465-be4b-9968edf19d9c.png)
icon-80
![icon-80](https://user-images.githubusercontent.com/9006111/139631509-a4bf519c-98f0-413f-82da-0047167e14c9.png)
icon-128
![icon-128](https://user-images.githubusercontent.com/9006111/139631513-69c91633-dc04-496d-b9a8-6752f5656e26.png)
icon-filled
![icon-filled](https://user-images.githubusercontent.com/9006111/139631515-adbf1d73-b1c5-453a-9fc0-484b687f5f2b.png)

**Comment by ties-taguchi** [comment]
@ties-makimura 
icoのzipをアップします．
[chilospeech_big.ico.zip](https://github.com/npocccties/chilospeech/files/7451524/chilospeech_big.ico.zip)

**Comment by ties-makimura** [comment]
#14 で対応
