### ISSUE TITLE
日本語のキーワードがjsonに反映されない

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chilospeech#41]
### そのバグについて

PowerPointに記載した日本語のキーワードをchilospeechで変換すると，生成されたjsonファイルにそのキーワードが反映されない．

### 再現手順

1.PowerPointに日本語のキーワードを記載

例：

```
Keywords: 日本語 333
```

2.PowerPointをchilospeechにアップして変換，ActionのZipファイルをダウンロード

3.jsonファイルを開くと，日本語のキーワードが反映されていない．
↑の例の場合は，333のみがキーワードに反映される

### 期待していた動作

日本語のキーワードもjsonに反映される．

**Comment by ties-makimura** [comment]
https://github.com/npocccties/chilospeech/commit/818db58a6a52cc4e87e421ac98b49ae176a17e61 で対応
