### ISSUE TITLE
GitHub Actionで警告（Annotations）が出る

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chilospeech#43]
### そのバグについて

GitHubActionの変換完了後，JOBの画面で以下の警告が複数表示される．

Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, trilom/file-changes-action@v1.2.4, actions/github-script@v4. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### 再現手順

1. CHiLO-SpeechのレポジトリでPPTと画像のフォルダをアップ
2. GitHub Actionsの変換を待つ
3. 変換後，ActionのJobページを確認する

### 期待していた動作

警告が出なくなる，警告の出る原因が解消される

**Comment by ties-makimura** [comment]
https://github.com/npocccties/chilospeech/commit/6e1bad227c597b88c91c6e56ee990449258b7aa2 で解決
