### ISSUE TITLE
WASM版: トピック一覧で voice, keyword などを表形式で表示する

### ISSUE THREAD

**Issue by acutus-fujii** [npocccties/chilospeech#46]
### どのような問題を解決する機能追加でしょうか?

WASM版でビデオを生成するとき、生成後のビデオファイルを再生しないと話者を確認できない。

### あなたが望む解決方法について書いてください

トピック一覧画面で、voice, keyword を表形式で表示してユーザが確認できるようにする。

### あなたが考えた別解について書いてください

PPTファイルを読み込んだ時点で、生成されるビデオや音声、メタ情報などを preview できることが望ましい。

### 本 issue を close する条件

- [x] コードに実装された。

### 追記・備考

関連: https://github.com/npocccties/ChibiCHiLO-private/issues/221
WASM版(2期) 開発作業と同時に作業する予定

**Comment by acutus-fujii** [comment]
## 実装した機能の表示例
![image](https://github.com/npocccties/chilospeech/assets/15375161/058cf08c-3269-4eb4-b735-bfee4db411db)

**Comment by ties-makimura** [comment]
881545751e846cc9d6b70d69f701dd8a0a0671ff で対応
