### ISSUE TITLE
CHiLO-Speechのアドインをfluentにする

### ISSUE THREAD

**Issue by horimasumi** [npocccties/chilospeech#6]
CHiLO-Speechのアドインを下図のようなデザインにする

## 機能

- [x] **話者：** プルダウンで話者の選択可能
- [x] **音声の確認：** 選択部分の合成音声が流れる
- [x] **よく使うタグ：**
　　マウスオーバ：タグの説明が表示される
　　クリック：タグががメモリにコピーされる
- [x] **リンク：** 別サイトに飛ぶ

## タグの説明の仕様

タグ | 説明 | コピーされる文字列
-- | -- | --
[break:"0.5s"] | 無音区間（息継ぎ） | [break:""]
(TIES)[ruby:"たいず"] | 読み | ()[ruby:""]
(音声)[kana:"オンセイ"] | アクセント | ()[kana:"　'　"]

## リンクの仕様

[CHiBi-CHiLOマニュアル](https://docs.cccties.org/chilospeech/)
[サポートされている SSML タグ](https://docs.aws.amazon.com/ja_jp/polly/latest/dg/supportedtags.html)
[What Is Speech Markdown?](https://www.speechmarkdown.org/basics/what/)

![add-in](https://user-images.githubusercontent.com/9005132/139398990-44f8ab32-acc0-44bf-b3f9-7f86672d0865.png)

**Comment by ties-taguchi** [comment]
修正案1（文字でタグの案内）
![add-in3](https://user-images.githubusercontent.com/9006111/139606707-b24709cc-2a2a-4537-94e4-1df2bfd9d454.png)

修正案2（アイコンの追加）
![add-in2](https://user-images.githubusercontent.com/9006111/139606710-75fba3ec-c46d-4950-9f6d-fc61e91600b2.png)

**Comment by ties-taguchi** [comment]
修正案1（文字でタグの案内）
![add-in2](https://user-images.githubusercontent.com/9006111/139606779-1e6b55c8-122b-450a-9170-7541341d2bdb.png)

修正案2（アイコンの追加）
![add-in3](https://user-images.githubusercontent.com/9006111/139606804-1558628a-45b2-4463-b2bb-bbe685a8fdac.png)

**Comment by horimasumi** [comment]
@ties-taguchi ＞アイコンを使うなら，標準的なアイコンが良いと思います．

**Comment by ties-taguchi** [comment]
通常時
![add-in4](https://user-images.githubusercontent.com/9006111/139628995-20d0ccb6-6951-45f9-a11e-d8c413419688.png)

クリック時
![add-in4-2](https://user-images.githubusercontent.com/9006111/139629032-931ccb14-055f-4381-be5b-9d1959065537.png)

**Comment by ties-taguchi** [comment]
@ties-makimura 
![break-1](https://user-images.githubusercontent.com/9006111/139631802-9958b5a8-5dfa-4400-9609-682d323d86b5.png)
![break-2](https://user-images.githubusercontent.com/9006111/139631804-9568547c-e2a5-4b85-a73a-effca69e41b4.png)
![kana-1](https://user-images.githubusercontent.com/9006111/139631805-1e3e7813-01bd-4b93-b91f-bef427cc2e7c.png)
![kana-2](https://user-images.githubusercontent.com/9006111/139631806-8acf6f81-bf8f-4482-92c1-37bde4083b60.png)
![ruby-1](https://user-images.githubusercontent.com/9006111/139631807-6980b6ca-8ff1-4fcd-8d18-b591511c5848.png)
![ruby-2](https://user-images.githubusercontent.com/9006111/139631808-79805f3f-124a-42ba-9ec1-6977ea4c98c3.png)
![音声の確認](https://user-images.githubusercontent.com/9006111/139631810-624a32e0-84d7-41cb-8d8e-81a469f73315.png)

**Comment by ties-makimura** [comment]
#14 で対応
