### ISSUE TITLE
合成音声ビデオ作成時、jsonに学習時間のデータを追加してほしい

### ISSUE THREAD

**Issue by ties-mitsuhashi** [npocccties/chilospeech#7]
### どのような問題を解決する機能追加でしょうか?

合成音声ビデオ作成システムで作成したZipをCHiBi-CHiLOにインポートするとき、jsonデータに学習時間が含まれないため、インポートしたCHiBi-CHiLOを見ると、学習時間が１秒未満となってしまう。

### あなたが望む解決方法について書いてください

CHiLO-SpeechでZipデータを作成するときに、jsonに自動的に学習時間のデータが追加される。

- [x] ppt2video
- [x] WASM版

### 追記・備考

![image](https://user-images.githubusercontent.com/8965947/131812048-7afbaf65-ea4b-475d-af6d-157ad86e0e8a.png)

**Comment by acutus-fujii** [comment]
既存の、学習時間の自動補完機能と同様に、トピックの timeRequired にはビデオ duration を整数に切り捨てた (Math.floorした) 値に設定する。

https://github.com/npocccties/chibichilo/blob/e21f04d9f9973bbb51212c15866221c1ea222464/components/organisms/TopicForm.tsx#L267-L289

**Comment by acutus-fujii** [comment]
ビデオが 1秒未満の場合、timeRequired が 0 になり、指定がないケースと区
別できないという問題があります。

chibichilo server/models/booksImportParams.ts で timeRequired は次のよ
うに規定されています。

- 0以上の整数のみ許容
- 設定がない、浮動少数の場合などは、デフォルト値 0 となる

```
export class ImportTopic {
  ...
  @IsInt({ message: "整数ではないか未設定です。" })
  @Min(0, { message: "0以上の整数を設定してください。" })
  timeRequired = 0;
```

**Comment by ties-makimura** [comment]
ビデオが 1秒未満の場合は timeRequired を 1 とする

**Comment by acutus-fujii** [comment]
ppt2video も対応しました。

**Comment by ties-mitsuhashi** [comment]
ありがとうございます．
ppt2video についても，

- jsonファイルにtimeRequiredが記載されている
- CHiBi-CHiLO一括登録時にtimeRequiredが学習時間に反映されている

を確認しました．
本issueをクローズします．
